name: Auto Increment Tag

on:
  push:
    branches:
      - master

jobs:
  auto_increment_tag:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            fetch-depth: 0


      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
            scheme: semver
            increment: patch

      - name: Create new tag
        uses: avakar/tag-and-release@v1
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}



